Repository ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t1-doacao-reacao-pmv, pull requests merged in 2023-10, with the labels that each got.

#41 Feat/footer template
  src/css/custom-footer.css
  src/css/index.css
  src/index.html
  src/js/components/footer.js
Labels: ready to merge

#39 Feat/responsive navbar
  src/css/nav-bar.css
  src/css/search-box.css
  src/css/theme.css
  src/js/components/navbar.js
  src/js/scroll-handler.js
Labels: ready to merge, feature

#43 feat/home page content v0
  src/css/custom-footer.css
  src/css/homepage.css
  src/index.html
Labels: good first issue, ready to merge, feature

#44 Refactor/navbar responsivity
  src/css/nav-bar.css
  src/css/search-box.css
  src/index.html
  src/js/components/navbar.js
Labels: bug, enhancement
